package org.tronhook.api.model.core;

public enum ReasonCodeModel {
	
	  REQUESTED,
	  BAD_PROTOCOL,
	  TOO_MANY_PEERS,
	  DUPLICATE_PEER,
	  INCOMPATIBLE_PROTOCOL,
	  NULL_IDENTITY,
	  PEER_QUITING,
	  UNEXPECTED_IDENTITY,
	  LOCAL_IDENTITY,
	  PING_TIMEOUT,
	  USER_REASON,
	  RESET,
	  SYNC_FAIL,
	  FETCH_FAIL,
	  BAD_TX,
	  BAD_BLOCK,
	  FORKED,
	  UNLINKABLE,
	  INCOMPATIBLE_VERSION,
	  INCOMPATIBLE_CHAIN,
	  TIME_OUT,
	  CONNECT_FAIL,
	  TOO_MANY_PEERS_WITH_SAME_IP,
	  UNKNOWN;

}
